"""Produtos do catálogo JP Doces para seed inicial."""

PRODUTOS_SEED = [
    # ── AMENDOIM ──────────────────────────────────────────────────────────
    {'codigo': '2221', 'nome': 'AMENDOIM DOCE DELÍCIA CROCANTE TRADIC 400G',          'categoria': 'AMENDOIM', 'preco': 8.50,  'unidade': 'UN'},
    {'codigo': '2575', 'nome': 'AMENDOIM DOCE DELÍCIA CROC SALSA E CEB PT 150G',      'categoria': 'AMENDOIM', 'preco': 4.50,  'unidade': 'UN'},
    {'codigo': '2216', 'nome': 'AMENDOIM CROCK RIO CROCANTE CEBOLA 30X60GR',          'categoria': 'AMENDOIM', 'preco': 32.00, 'unidade': 'CX'},
    {'codigo': '2222', 'nome': 'AMENDOIM DOCE DELÍCIA JAPONÊS 400G',                  'categoria': 'AMENDOIM', 'preco': 8.50,  'unidade': 'UN'},
    {'codigo': '2576', 'nome': 'AMENDOIM DOCE DELÍCIA CROC TRADICIONAL PT 150G',      'categoria': 'AMENDOIM', 'preco': 4.50,  'unidade': 'UN'},
    {'codigo': '2214', 'nome': 'AMENDOIM CROCK RIO CROCANTE NATURAL 30X60GR',         'categoria': 'AMENDOIM', 'preco': 32.00, 'unidade': 'CX'},
    {'codigo': '2224', 'nome': 'AMENDOIM DOCE DELÍCIA OVINHO 400G',                   'categoria': 'AMENDOIM', 'preco': 8.50,  'unidade': 'UN'},
    {'codigo': '2580', 'nome': 'AMENDOIM DOCE DELÍCIA FRITO C/PELE SALG PT 160G',     'categoria': 'AMENDOIM', 'preco': 4.80,  'unidade': 'UN'},
    {'codigo': '2215', 'nome': 'AMENDOIM CROCK RIO CROCANTE PIMENTA 30X60GR',         'categoria': 'AMENDOIM', 'preco': 32.00, 'unidade': 'CX'},
    {'codigo': '2218', 'nome': 'AMENDOIM DOCE DELÍCIA BANDA S/ PELE C/SAL 400G',      'categoria': 'AMENDOIM', 'preco': 8.00,  'unidade': 'UN'},
    {'codigo': '2219', 'nome': 'AMENDOIM DOCE DELÍCIA BANDA S/ PELE S/SAL 400G',      'categoria': 'AMENDOIM', 'preco': 8.00,  'unidade': 'UN'},
    {'codigo': '1312', 'nome': 'AMENDOIM ZÉZINHO FELIPE SALGADO PT C/ 20 UN',         'categoria': 'AMENDOIM', 'preco': 18.00, 'unidade': 'PT'},
    {'codigo': '1306', 'nome': 'AMENDOIM ZÉZINHO FELIPE DOCE PT C/ 15 UN',            'categoria': 'AMENDOIM', 'preco': 15.00, 'unidade': 'PT'},
    {'codigo': '2220', 'nome': 'AMENDOIM DOCE DELÍCIA BLANCHEADO C/ALHO 400G',        'categoria': 'AMENDOIM', 'preco': 8.50,  'unidade': 'UN'},
    {'codigo': '2572', 'nome': 'AMENDOIM DOCE DELÍCIA BANDA TORRAD C/ SAL PT 160G',   'categoria': 'AMENDOIM', 'preco': 4.80,  'unidade': 'UN'},
    {'codigo': '2571', 'nome': 'AMENDOIM DOCE DELÍCIA BANDA TORRAD S/ SAL PT 160G',   'categoria': 'AMENDOIM', 'preco': 4.80,  'unidade': 'UN'},
    {'codigo': '2574', 'nome': 'AMENDOIM DOCE DELÍCIA JAPONÊS PT 150G',               'categoria': 'AMENDOIM', 'preco': 4.50,  'unidade': 'UN'},
    {'codigo': '2579', 'nome': 'AMENDOIM DOCE DELÍCIA PRALINE PT 140G',               'categoria': 'AMENDOIM', 'preco': 4.50,  'unidade': 'UN'},
    {'codigo': '1311', 'nome': 'AMENDOIM FELIPE SALGADO PCT 20X40G',                  'categoria': 'AMENDOIM', 'preco': 20.00, 'unidade': 'PCT'},
    {'codigo': '1305', 'nome': 'AMENDOIM FELIPE DOCE PCT 20X53G',                     'categoria': 'AMENDOIM', 'preco': 20.00, 'unidade': 'PCT'},
    {'codigo': '1303', 'nome': 'AMENDOIM SALGAMAR C/ PELE ESPETO 40X35G',             'categoria': 'AMENDOIM', 'preco': 28.00, 'unidade': 'ESP'},
    {'codigo': '1309', 'nome': 'AMENDOIM SALGAMAR S/ PELE ESPETO 40X35G',             'categoria': 'AMENDOIM', 'preco': 28.00, 'unidade': 'ESP'},
    {'codigo': '1310', 'nome': 'AMENDOIM SALGAMAR S/ PELE CARTELA 20X35G',            'categoria': 'AMENDOIM', 'preco': 16.00, 'unidade': 'CT'},
    {'codigo': '1302', 'nome': 'AMENDOIM SALGAMAR C/ PELE CARTELA 20X35G',            'categoria': 'AMENDOIM', 'preco': 16.00, 'unidade': 'CT'},
    {'codigo': '1307', 'nome': 'AMENDOIM SALGAMAR JAPONÊS CARTELA 20X35G',            'categoria': 'AMENDOIM', 'preco': 16.00, 'unidade': 'CT'},
    {'codigo': '1308', 'nome': 'AMENDOIM SALGAMAR OVINHO CARTELA 20X20G',             'categoria': 'AMENDOIM', 'preco': 14.00, 'unidade': 'CT'},

    # ── BALA ──────────────────────────────────────────────────────────────
    {'codigo': '2428', 'nome': 'BALA DADINHO 600G',                                   'categoria': 'BALA', 'preco': 9.50,  'unidade': 'UN'},
    {'codigo': '2671', 'nome': 'BALA SANTA FÉ MEL E GENGIBRE 450G',                   'categoria': 'BALA', 'preco': 8.50,  'unidade': 'UN'},
    {'codigo': '2673', 'nome': 'BALA SANTA FÉ AMENDOIM CROC 500G',                    'categoria': 'BALA', 'preco': 9.00,  'unidade': 'UN'},
    {'codigo': '2426', 'nome': 'BALA DIMBINHO HORTELÃ 600G',                          'categoria': 'BALA', 'preco': 9.50,  'unidade': 'UN'},
    {'codigo': '2564', 'nome': 'BALA SANTA FÉ AMENDOIM MASTIG 600G',                  'categoria': 'BALA', 'preco': 10.00, 'unidade': 'UN'},
    {'codigo': '2319', 'nome': 'BALA SANTA FÉ CANELA 600G',                           'categoria': 'BALA', 'preco': 9.50,  'unidade': 'UN'},
    {'codigo': '2314', 'nome': 'BALA DIMBINHO FRUTAS SORTIDAS 600G',                  'categoria': 'BALA', 'preco': 9.50,  'unidade': 'UN'},
    {'codigo': '2321', 'nome': 'BALA SANTA FÉ HORTELÃ 600G',                          'categoria': 'BALA', 'preco': 9.50,  'unidade': 'UN'},
    {'codigo': '2320', 'nome': 'BALA SANTA FÉ FRUTAS SORTIDAS 600G',                  'categoria': 'BALA', 'preco': 9.50,  'unidade': 'UN'},
    {'codigo': '1300', 'nome': 'BALA KADOCES QUEBRA QUEIXO PT 600G',                  'categoria': 'BALA', 'preco': 11.00, 'unidade': 'UN'},
    {'codigo': '2315', 'nome': 'BALA DIMBINHO YOGURTE MORANGO 600G',                  'categoria': 'BALA', 'preco': 9.50,  'unidade': 'UN'},
    {'codigo': '2316', 'nome': 'BALA DIMBINHO YOGURTE FRUTAS 600G',                   'categoria': 'BALA', 'preco': 9.50,  'unidade': 'UN'},
    {'codigo': '2422', 'nome': 'BALA FINI TUBES UVA 12X15G',                          'categoria': 'BALA', 'preco': 22.00, 'unidade': 'CX'},
    {'codigo': '2416', 'nome': 'BALA FINI TUBES MORANGO E NATA 12X15G',               'categoria': 'BALA', 'preco': 22.00, 'unidade': 'CX'},
    {'codigo': '2464', 'nome': 'BALA FINI TUBES 3 CORES 12X17G',                      'categoria': 'BALA', 'preco': 22.00, 'unidade': 'CX'},
    {'codigo': '2415', 'nome': 'BALA FINI TUBES MORANGO E NATA CÍTRICO 12X15G',       'categoria': 'BALA', 'preco': 22.00, 'unidade': 'CX'},
    {'codigo': '2706', 'nome': 'BALA DROPS HALLS MELANCIA DP 21 UNIDADES',            'categoria': 'BALA', 'preco': 38.00, 'unidade': 'DP'},
    {'codigo': '2418', 'nome': 'BALA FINI TUBES TUTTI-FRUT CÍTRICO 12X15G',           'categoria': 'BALA', 'preco': 22.00, 'unidade': 'CX'},
    {'codigo': '2417', 'nome': 'BALA FINI TUBES PINTA LÍNGUA 12X15G',                 'categoria': 'BALA', 'preco': 22.00, 'unidade': 'CX'},
    {'codigo': '2326', 'nome': 'BALA DROPS HALLS CEREJA DP 21 UNIDADES',              'categoria': 'BALA', 'preco': 38.00, 'unidade': 'DP'},
    {'codigo': '2421', 'nome': 'BALA FINI TUBES UVA CÍTRICO 12X15G',                  'categoria': 'BALA', 'preco': 22.00, 'unidade': 'CX'},
    {'codigo': '2625', 'nome': 'BALA DROPS HALLS MORANGO DP 21 UNIDADES',             'categoria': 'BALA', 'preco': 38.00, 'unidade': 'DP'},
    {'codigo': '2670', 'nome': 'BALA SANTA FÉ YOGURTE MORANGO 600G',                  'categoria': 'BALA', 'preco': 9.50,  'unidade': 'UN'},
    {'codigo': '2420', 'nome': 'BALA FINI TUBES TWISTER 12X15G',                      'categoria': 'BALA', 'preco': 22.00, 'unidade': 'CX'},
    {'codigo': '2624', 'nome': 'BALA DROPS HALLS EXTRA FORTE DP 21 UNIDADES',         'categoria': 'BALA', 'preco': 38.00, 'unidade': 'DP'},
    {'codigo': '2628', 'nome': 'BALA DROPS HALLS MENTA DP 21 UNIDADES',               'categoria': 'BALA', 'preco': 38.00, 'unidade': 'DP'},
    {'codigo': '2658', 'nome': 'BALA DROPS HALLS UVA VERDE DP 21 UNIDADES',           'categoria': 'BALA', 'preco': 38.00, 'unidade': 'DP'},

    # ── CHICLETE ──────────────────────────────────────────────────────────
    {'codigo': '2537', 'nome': 'CHICLETÃO DANNY TUTTI-FRUT DP C/24',                  'categoria': 'CHICLETE', 'preco': 22.00, 'unidade': 'DP'},
    {'codigo': '2242', 'nome': 'CHICLETE MONDELEZ TRIDENT MORANGO DP 21 UN',          'categoria': 'CHICLETE', 'preco': 42.00, 'unidade': 'DP'},
    {'codigo': '2350', 'nome': 'CHICLETE ARCOR POOSH TUTTI-FRUT CX C/40',             'categoria': 'CHICLETE', 'preco': 28.00, 'unidade': 'CX'},
    {'codigo': '2542', 'nome': 'CHICLETÃO DANNY UVA DP C/24',                         'categoria': 'CHICLETE', 'preco': 22.00, 'unidade': 'DP'},
    {'codigo': '2347', 'nome': 'CHICLETE ARCOR POOSH HORTELÃ CX C/40',                'categoria': 'CHICLETE', 'preco': 28.00, 'unidade': 'CX'},
    {'codigo': '2588', 'nome': 'CHICLETE MONDELEZ TRIDENT TUTTI-FRUT DP 21 UN',       'categoria': 'CHICLETE', 'preco': 42.00, 'unidade': 'DP'},
    {'codigo': '2541', 'nome': 'CHICLETÃO DANNY YOGURTE DE MORANGO DP C/24',          'categoria': 'CHICLETE', 'preco': 22.00, 'unidade': 'DP'},
    {'codigo': '2348', 'nome': 'CHICLETE ARCOR POOSH MORANGO CX C/40',                'categoria': 'CHICLETE', 'preco': 28.00, 'unidade': 'CX'},
    {'codigo': '2240', 'nome': 'CHICLETE MONDELEZ TRIDENT HORTELÃ DP 21 UN',          'categoria': 'CHICLETE', 'preco': 42.00, 'unidade': 'DP'},
    {'codigo': '2540', 'nome': 'CHICLETÃO DANNY CEREJA DP C/24',                      'categoria': 'CHICLETE', 'preco': 22.00, 'unidade': 'DP'},
    {'codigo': '2351', 'nome': 'CHICLETE ARCOR POOSH UVA CX C/40',                    'categoria': 'CHICLETE', 'preco': 28.00, 'unidade': 'CX'},
    {'codigo': '2238', 'nome': 'CHICLETE MONDELEZ TRIDENT MENTA DP 21 UN',            'categoria': 'CHICLETE', 'preco': 42.00, 'unidade': 'DP'},
    {'codigo': '2539', 'nome': 'CHICLETÃO DANNY MELANCIA DP C/24',                    'categoria': 'CHICLETE', 'preco': 22.00, 'unidade': 'DP'},
    {'codigo': '2239', 'nome': 'CHICLETE MONDELEZ TRIDENT MELANCIA DP 21 UN',         'categoria': 'CHICLETE', 'preco': 42.00, 'unidade': 'DP'},
    {'codigo': '2538', 'nome': 'CHICLETÃO DANNY MORANGO DP C/24',                     'categoria': 'CHICLETE', 'preco': 22.00, 'unidade': 'DP'},
    {'codigo': '2241', 'nome': 'CHICLETE MONDELEZ TRIDENT CANELA DP 21 UN',           'categoria': 'CHICLETE', 'preco': 42.00, 'unidade': 'DP'},
    {'codigo': '2589', 'nome': 'CHICLETE MONDELEZ TRIDENT FRESH CEREJA DP 21 UN',     'categoria': 'CHICLETE', 'preco': 42.00, 'unidade': 'DP'},
    {'codigo': '2586', 'nome': 'CHICLETE MONDELEZ TRIDENT FRESH INTENSE DP 21 UN',    'categoria': 'CHICLETE', 'preco': 42.00, 'unidade': 'DP'},
    {'codigo': '2587', 'nome': 'CHICLETE MONDELEZ TRIDENT FRESH HERBAL DP 21 UN',     'categoria': 'CHICLETE', 'preco': 42.00, 'unidade': 'DP'},

    # ── PIRULITO ──────────────────────────────────────────────────────────
    {'codigo': '2399', 'nome': 'PIRULITO POP KISS BLACK PCT 500G',                    'categoria': 'PIRULITO', 'preco': 14.00, 'unidade': 'PCT'},
    {'codigo': '2400', 'nome': 'PIRULITO POP KISS CEREJA PCT 500G',                   'categoria': 'PIRULITO', 'preco': 14.00, 'unidade': 'PCT'},
    {'codigo': '2430', 'nome': 'PIRULITO POP KISS MELANCIA PCT 500G',                 'categoria': 'PIRULITO', 'preco': 14.00, 'unidade': 'PCT'},
    {'codigo': '2401', 'nome': 'PIRULITO POP KISS MARACUJÁ PCT 500G',                 'categoria': 'PIRULITO', 'preco': 14.00, 'unidade': 'PCT'},
    {'codigo': '2546', 'nome': 'PIRULITO SANTA FÉ BIG POP FRAMBOESA 50X10G',          'categoria': 'PIRULITO', 'preco': 22.00, 'unidade': 'CX'},
    {'codigo': '2431', 'nome': 'PIRULITO POP KISS FRAMBOESA PCT 500G',                'categoria': 'PIRULITO', 'preco': 14.00, 'unidade': 'PCT'},
    {'codigo': '2547', 'nome': 'PIRULITO SANTA FÉ BIG POP CEREJA 50X10G',             'categoria': 'PIRULITO', 'preco': 22.00, 'unidade': 'CX'},
    {'codigo': '2467', 'nome': 'PIRULITO POP KISS ALGODÃO DOCE PCT 500G',             'categoria': 'PIRULITO', 'preco': 14.00, 'unidade': 'PCT'},
    {'codigo': '2545', 'nome': 'PIRULITO SANTA FÉ BIG POP TUTTI-FRUT 50X10G',         'categoria': 'PIRULITO', 'preco': 22.00, 'unidade': 'CX'},
    {'codigo': '2398', 'nome': 'PIRULITO POP KISS BEIJA MAIS PCT 500G',               'categoria': 'PIRULITO', 'preco': 14.00, 'unidade': 'PCT'},
    {'codigo': '2369', 'nome': 'PIRULITO FLOPITO CORAÇÃO VERMELHO PCT 500G',          'categoria': 'PIRULITO', 'preco': 14.00, 'unidade': 'PCT'},

    # ── CHOCOLATE ─────────────────────────────────────────────────────────
    {'codigo': '2688', 'nome': 'CHOCOLATE NESTLÉ CHARGE DP 30X40G',                   'categoria': 'CHOCOLATE', 'preco': 65.00, 'unidade': 'DP'},
    {'codigo': '2689', 'nome': 'CHOCOLATE TRENTO MORANGO DP 16X32G',                  'categoria': 'CHOCOLATE', 'preco': 32.00, 'unidade': 'DP'},
    {'codigo': '2584', 'nome': 'CHOCOLATE TRENTO BRANCO DARK DP 16X32G',              'categoria': 'CHOCOLATE', 'preco': 32.00, 'unidade': 'DP'},
    {'codigo': '2512', 'nome': 'BRIGADEIROS DO DEDINHO SORTIDO CAIXA C/ 50 UN',       'categoria': 'CHOCOLATE', 'preco': 45.00, 'unidade': 'CX'},
    {'codigo': '2701', 'nome': 'CHOCOLATE TRENTO DARK DP 16X32G',                     'categoria': 'CHOCOLATE', 'preco': 32.00, 'unidade': 'DP'},
    {'codigo': '2622', 'nome': 'CHOCOLATE TRENTO MARACUJÁ DP 16X32G',                 'categoria': 'CHOCOLATE', 'preco': 32.00, 'unidade': 'DP'},
    {'codigo': '2581', 'nome': 'CHOCOLATE TRENTO MASSIMO NUTS DP 16X25G',             'categoria': 'CHOCOLATE', 'preco': 35.00, 'unidade': 'DP'},
    {'codigo': '2611', 'nome': 'CHOCOLATE NESTLÉ CHOKITO DP 30X32G',                  'categoria': 'CHOCOLATE', 'preco': 58.00, 'unidade': 'DP'},
    {'codigo': '2631', 'nome': 'CHOCOLATE TRENTO AVELÃ DP 16X32G',                    'categoria': 'CHOCOLATE', 'preco': 32.00, 'unidade': 'DP'},
    {'codigo': '2507', 'nome': 'CHOCOLATE NESTLÉ PRESTÍGIO DP 30X33G',                'categoria': 'CHOCOLATE', 'preco': 58.00, 'unidade': 'DP'},
    {'codigo': '2618', 'nome': 'CHOCOLATE TRENTO MASSIMO DUO DP 16X25G',              'categoria': 'CHOCOLATE', 'preco': 35.00, 'unidade': 'DP'},
    {'codigo': '2675', 'nome': 'CHOCOLATE TRENTO TORTA DE LIMÃO DP 16X32G',           'categoria': 'CHOCOLATE', 'preco': 32.00, 'unidade': 'DP'},
    {'codigo': '2233', 'nome': 'CHOCOLATE NESTLÉ SUFLAIR AO LEITE DP 20X50G',         'categoria': 'CHOCOLATE', 'preco': 52.00, 'unidade': 'DP'},
    {'codigo': '2617', 'nome': 'CHOCOLATE TRENTO MASSIMO COOKIES DP 16X25G',          'categoria': 'CHOCOLATE', 'preco': 35.00, 'unidade': 'DP'},
    {'codigo': '2636', 'nome': 'CHOCOLATE TRENTO DUO DP 16X32G',                      'categoria': 'CHOCOLATE', 'preco': 32.00, 'unidade': 'DP'},
    {'codigo': '2236', 'nome': 'CHOCOLATE SNICKERS ORIGINAL DP 20X45G',               'categoria': 'CHOCOLATE', 'preco': 58.00, 'unidade': 'DP'},
    {'codigo': '2237', 'nome': 'CHOCOLATE TWIX ORIGINAL DP 30X15G',                   'categoria': 'CHOCOLATE', 'preco': 55.00, 'unidade': 'DP'},
    {'codigo': '2635', 'nome': 'CHOCOLATE LACTA OURO BRANCO PACOTE 1KG',              'categoria': 'CHOCOLATE', 'preco': 38.00, 'unidade': 'PCT'},
    {'codigo': '2655', 'nome': 'CHOCOLATE LACTA SONHO DE VALSA PACOTE 1KG',           'categoria': 'CHOCOLATE', 'preco': 38.00, 'unidade': 'PCT'},
    {'codigo': '2508', 'nome': 'CHOCOLATE NESTLÉ KIT KAT DP 24X41,5G',               'categoria': 'CHOCOLATE', 'preco': 75.00, 'unidade': 'DP'},
    {'codigo': '2660', 'nome': 'CHOCOLATE NESTLÉ KIT KAT DARK DP 24X41,5G',          'categoria': 'CHOCOLATE', 'preco': 75.00, 'unidade': 'DP'},
    {'codigo': '2659', 'nome': 'CHOCOLATE NESTLÉ KIT KAT WHITE DP 24X41,5G',         'categoria': 'CHOCOLATE', 'preco': 75.00, 'unidade': 'DP'},

    # ── SALGADINHO ────────────────────────────────────────────────────────
    {'codigo': '2524', 'nome': 'BATATA ONDULADA WANFLO ORIGINAL CX 12X40G',           'categoria': 'SALGADINHO', 'preco': 28.00, 'unidade': 'CX'},
    {'codigo': '2526', 'nome': 'BATATA ONDULADA WANFLO CHURRAS CX 12X40G',            'categoria': 'SALGADINHO', 'preco': 28.00, 'unidade': 'CX'},
    {'codigo': '2640', 'nome': 'BATATA ONDULADA WANFLO CHEDDAR E BACON CX 12X40G',   'categoria': 'SALGADINHO', 'preco': 28.00, 'unidade': 'CX'},
    {'codigo': '2409', 'nome': 'SALGADINHO PINGOLITOS PRESUNTO FD',                   'categoria': 'SALGADINHO', 'preco': 18.00, 'unidade': 'FD'},
    {'codigo': '2402', 'nome': 'PURURUCA BISCONOBRE BACON LISTRADA 20X60G',           'categoria': 'SALGADINHO', 'preco': 22.00, 'unidade': 'CX'},
    {'codigo': '2491', 'nome': 'PIPOCA FLOCÃO FORMIGÃO 30X40G',                       'categoria': 'SALGADINHO', 'preco': 24.00, 'unidade': 'CX'},
    {'codigo': '2406', 'nome': 'SALGADINHO PINGOLITOS BACON FD',                      'categoria': 'SALGADINHO', 'preco': 18.00, 'unidade': 'FD'},
    {'codigo': '2407', 'nome': 'SALGADINHO PINGOLITOS CEBOLA FD',                     'categoria': 'SALGADINHO', 'preco': 18.00, 'unidade': 'FD'},
    {'codigo': '2403', 'nome': 'PURURUCA BISCONOBRE CEBOLA E SALSA 20X60G',           'categoria': 'SALGADINHO', 'preco': 22.00, 'unidade': 'CX'},
    {'codigo': '2525', 'nome': 'BATATA ONDULADA WANFLO CEBOLA CX 12X40G',             'categoria': 'SALGADINHO', 'preco': 28.00, 'unidade': 'CX'},
    {'codigo': '2411', 'nome': 'SALGADINHO PINGOLITOS REQUEIJÃO FD',                  'categoria': 'SALGADINHO', 'preco': 18.00, 'unidade': 'FD'},
    {'codigo': '2392', 'nome': 'PIPOCA DOCE FORMIGÃO 10X120G',                        'categoria': 'SALGADINHO', 'preco': 22.00, 'unidade': 'CX'},
    {'codigo': '2393', 'nome': 'PIPOCA DOCE FORMIGÃO 30X40G',                         'categoria': 'SALGADINHO', 'preco': 24.00, 'unidade': 'CX'},
    {'codigo': '2408', 'nome': 'SALGADINHO PINGOLITOS CHURRASCO FD',                  'categoria': 'SALGADINHO', 'preco': 18.00, 'unidade': 'FD'},
    {'codigo': '2410', 'nome': 'SALGADINHO PINGOLITOS QUEIJO FD',                     'categoria': 'SALGADINHO', 'preco': 18.00, 'unidade': 'FD'},
    {'codigo': '2708', 'nome': 'SALGADINHO FRITOP REQUEIJÃO CX 10X200G',              'categoria': 'SALGADINHO', 'preco': 32.00, 'unidade': 'CX'},
    {'codigo': '2707', 'nome': 'SALGADINHO FRITOP CEBOLA E SALSA CX 10X200G',        'categoria': 'SALGADINHO', 'preco': 32.00, 'unidade': 'CX'},

    # ── POTE ──────────────────────────────────────────────────────────────
    {'codigo': '1128', 'nome': 'MOLECÃO ZÉZINHO POTE COM 20 UN',                      'categoria': 'POTE', 'preco': 22.00, 'unidade': 'PT'},
    {'codigo': '1129', 'nome': 'PINGO DE LEITE ZÉZINHO POTE COM 20 UN',               'categoria': 'POTE', 'preco': 22.00, 'unidade': 'PT'},
    {'codigo': '1328', 'nome': 'BANANA PALITO ZÉZINHO POTE COM 20 UN',                'categoria': 'POTE', 'preco': 22.00, 'unidade': 'PT'},
    {'codigo': '1119', 'nome': 'PAÇOCA GIBI ZÉZINHO POTE COM 20 UN',                  'categoria': 'POTE', 'preco': 22.00, 'unidade': 'PT'},
    {'codigo': '1130', 'nome': 'DOCE QUEBRA-QUEIXO ZÉZINHO POTE COM 20 UN',           'categoria': 'POTE', 'preco': 22.00, 'unidade': 'PT'},
    {'codigo': '1114', 'nome': 'GELEIA DE BANANA ZÉZINHO POTE COM 20 UN',             'categoria': 'POTE', 'preco': 22.00, 'unidade': 'PT'},
    {'codigo': '1101', 'nome': 'AB MISTO ZÉZINHO POTE COM 20 UN',                     'categoria': 'POTE', 'preco': 22.00, 'unidade': 'PT'},
    {'codigo': '1105', 'nome': 'COCADA MISTA ZÉZINHO POTE COM 20 UN',                 'categoria': 'POTE', 'preco': 22.00, 'unidade': 'PT'},
    {'codigo': '1118', 'nome': 'PAÇOCA GIBI ZÉZINHO GA POTE COM 20 UN',               'categoria': 'POTE', 'preco': 22.00, 'unidade': 'PT'},
    {'codigo': '1100', 'nome': 'AB C/ COCO ZÉZINHO POTE COM 20 UN',                   'categoria': 'POTE', 'preco': 22.00, 'unidade': 'PT'},
    {'codigo': '1112', 'nome': 'FONDANT DE LEITE MISTO ZÉZINHO DD PT C/20',           'categoria': 'POTE', 'preco': 22.00, 'unidade': 'PT'},
    {'codigo': '2155', 'nome': 'AB MISTO DOCE DELÍCIA POTE COM 20 UN',                'categoria': 'POTE', 'preco': 22.00, 'unidade': 'PT'},
    {'codigo': '1122', 'nome': 'PAÇOCA ROLHA ZÉZINHO POTE COM 20 UN',                 'categoria': 'POTE', 'preco': 22.00, 'unidade': 'PT'},
    {'codigo': '1127', 'nome': 'PÉ DE MOÇA ZÉZINHO POTE COM 20 UN',                   'categoria': 'POTE', 'preco': 22.00, 'unidade': 'PT'},
    {'codigo': '2154', 'nome': 'CAJUZINHO DOCE DELÍCIA POTE COM 20 UN',               'categoria': 'POTE', 'preco': 22.00, 'unidade': 'PT'},
    {'codigo': '1115', 'nome': 'GELEIA DE FRUTAS ZÉZINHO POTE COM 20 UN',             'categoria': 'POTE', 'preco': 22.00, 'unidade': 'PT'},
    {'codigo': '1106', 'nome': 'BANANA COPINHO ZÉZINHO POTE COM 20 UN',               'categoria': 'POTE', 'preco': 22.00, 'unidade': 'PT'},
    {'codigo': '1124', 'nome': 'PÉ CROCANTE ZÉZINHO POTE COM 20 UN',                  'categoria': 'POTE', 'preco': 22.00, 'unidade': 'PT'},
    {'codigo': '1103', 'nome': 'BANANA DA ROÇA ZÉZINHO POTE COM 20 UN',               'categoria': 'POTE', 'preco': 22.00, 'unidade': 'PT'},
    {'codigo': '1116', 'nome': 'GELEIA DE MOCOTÓ ZÉZINHO POTE COM 18 UN',             'categoria': 'POTE', 'preco': 20.00, 'unidade': 'PT'},
    {'codigo': '2151', 'nome': 'COCADA MISTA DOCE DELÍCIA POTE COM 20 UN',            'categoria': 'POTE', 'preco': 22.00, 'unidade': 'PT'},
    {'codigo': '1409', 'nome': 'PINGO DE LEITE PAULISTANO POTE COM 50 UN',            'categoria': 'POTE', 'preco': 38.00, 'unidade': 'PT'},
    {'codigo': '1140', 'nome': 'BRIGADEIRO FAMOSO POTE COM 20 UN',                    'categoria': 'POTE', 'preco': 22.00, 'unidade': 'PT'},

    # ── DIVERSOS ──────────────────────────────────────────────────────────
    {'codigo': '171',  'nome': 'DOCE DE BATATA GALVANI CAIXA COM 60 UN',              'categoria': 'DIVERSOS', 'preco': 28.00, 'unidade': 'CX'},
    {'codigo': '2206', 'nome': 'PAÇOCA ROLHA NICOLINHA PT 30X300G',                   'categoria': 'DIVERSOS', 'preco': 22.00, 'unidade': 'PT'},
    {'codigo': '1232', 'nome': 'PORTÃO DE CAMBUÍ CHOC C/ COCO DP 30X33G',             'categoria': 'DIVERSOS', 'preco': 55.00, 'unidade': 'DP'},
    {'codigo': '1204', 'nome': 'BANANA FAMOSO C/ AÇUCAR DP C/ 24',                    'categoria': 'DIVERSOS', 'preco': 22.00, 'unidade': 'DP'},
    {'codigo': '173',  'nome': 'PAÇOCA GIBI GALVANI ESPETO 50X90G',                   'categoria': 'DIVERSOS', 'preco': 32.00, 'unidade': 'ESP'},
    {'codigo': '2204', 'nome': 'PAÇOCA ROLHA NICOLINHA PT 12X504G',                   'categoria': 'DIVERSOS', 'preco': 55.00, 'unidade': 'PT'},
    {'codigo': '1233', 'nome': 'PORTÃO DE CAMBUÍ DOCE DE LEITE DP 40X25G',            'categoria': 'DIVERSOS', 'preco': 48.00, 'unidade': 'DP'},
    {'codigo': '2364', 'nome': 'ICEGURTT SORTIDOS PCT 50 UN',                         'categoria': 'DIVERSOS', 'preco': 28.00, 'unidade': 'PCT'},
    {'codigo': '1205', 'nome': 'BANANA FAMOSO S/ AÇUCAR DP C/ 24',                    'categoria': 'DIVERSOS', 'preco': 22.00, 'unidade': 'DP'},
    {'codigo': '163',  'nome': 'DOCE DE LEITE DOÇURA DA FAZENDA ESPETO C/ 40 UN',     'categoria': 'DIVERSOS', 'preco': 30.00, 'unidade': 'ESP'},
    {'codigo': '2213', 'nome': 'PAÇOCA MORENINHA DO RIO DP 50X20G',                   'categoria': 'DIVERSOS', 'preco': 28.00, 'unidade': 'DP'},
    {'codigo': '1203', 'nome': 'DOCE DE BATATA GALVANI DISPLAY COM 30 UN',            'categoria': 'DIVERSOS', 'preco': 18.00, 'unidade': 'DP'},
    {'codigo': '1208', 'nome': 'PAÇOCA GALVANI AMENDOCLASS DP C/ 50 UN',              'categoria': 'DIVERSOS', 'preco': 32.00, 'unidade': 'DP'},
    {'codigo': '1229', 'nome': 'DOCE DE LEITE AMOR DE MINAS CHUP-CHUP PCT 50X30G',   'categoria': 'DIVERSOS', 'preco': 30.00, 'unidade': 'PCT'},
    {'codigo': '181',  'nome': 'DOCE PÉ DE MOÇA ZÉZINHO CX 30 UN X 180G',            'categoria': 'DIVERSOS', 'preco': 45.00, 'unidade': 'CX'},
    {'codigo': '1201', 'nome': 'COCADA CREMOSA LEITE E MEL BANDEJA C/ 12 UN',         'categoria': 'DIVERSOS', 'preco': 18.00, 'unidade': 'BD'},
]
